# Generated by Django 4.2 on 2024-12-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_orders_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amountpaid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='paymentstatus',
        ),
    ]
